{% set name = "pyramid_debugtoolbar" %}
{% set version = "4.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71e888d349c85fcca12b3e6dc4c7ae8e3f02a1d5acc05154fd9ba8c7f661b43d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7
    - pyramid >=1.4
    - pyramid_mako >=0.3.1
    - repoze.lru
    - pygments

test:
  imports:
    - pyramid_debugtoolbar

about:
  home: https://trypyramid.com
  license: LicenseRef-Pylons
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Pyramid Web Framework, a Pylons project
  doc_url: https://docs.pylonsproject.org/projects/pyramid_mako/en/latest/
  dev_url: https://github.com/Pylons/pyramid_mako

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
