{% set name = "pyramid_debugtoolbar" %}
{% set version = "4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a1fd20bad4b8a1172f0ef4d22191ba382181206d0e566ffcf03d066b88429d7

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pyramid >=1.4
    - pyramid_mako >=0.3.1
    - repoze.lru
    - pygments

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyramid_debugtoolbar

about:
  home: https://trypyramid.com
  license: LicenseRef-Pylons
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Pyramid Web Framework, a Pylons project
  doc_url: https://docs.pylonsproject.org/projects/pyramid_mako/en/latest/
  dev_url: https://github.com/Pylons/pyramid_mako

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
